### ISSUE TITLE
map cannot be loaded after sign in.

### ISSUE THREAD

**Issue by rongqiibri** [aws-samples/aws-serverless-workshops#131] opened 2018-09-11 20:01 UTC
page source showed error: 

[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (amazon-cognito-identity.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (aws-cognito-sdk.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (aws-cognito-sdk.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (amazon-cognito-identity.min.js.map, line 0)

Thanks

**Comment by rongqiibri** [comment] 2018-09-11 20:49
I registered a new account with another email and everything worked fine.

**Comment by mikedeck** [comment] 2018-09-12 01:44
Hmm, I'm not sure why the resources have a ".map" suffix. That is likely the root cause here. Changing your cognito user shouldn't matter as those resources are being loaded from S3 and the credentials retrieved from Cognito aren't used to authenticate anything against S3.

Are you still getting this error if you use the original user? Can you reproduce the error at all? If so, can you open the network tab within the developer tools of your browser and see exactly what the URL is that's being requested and returning a 403?

**Comment by rongqiibri** [comment] 2018-09-12 16:15
> Hmm, I'm not sure why the resources have a ".map" suffix. That is likely the root cause here. Changing your cognito user shouldn't matter as those resources are being loaded from S3 and the credentials retrieved from Cognito aren't used to authenticate anything against S3.
> 
> Are you still getting this error if you use the original user? Can you reproduce the error at all? If so, can you open the network tab within the developer tools of your browser and see exactly what the URL is that's being requested and returning a 403?

Thanks!
The site is : [Error] Failed to load resource: the server responded with a status of 403 (Forbidden) https://s3.us-east-2.amazonaws.com/wilddrydes-XXX-xx/js/vendor/amazon-cognito-identity.min.js.map
Access was denied. 
But the page source did say: <h3 class="panel-title">Successfully Authenticated!</h3>
I also tried to sign in with those 2 different account and neither worked for me today. I even used another email account and also gave me the same error.

**Comment by mikedeck** [comment] 2018-09-12 17:20
Is this happening when you are viewing ride.html? Can you view the raw source for that page and see if there is a line that says: `<script src="js/vendor/aws-cognito-sdk.min.js"></script>`

I'm guessing somehow that got changed to include the ".map" suffix on the src path.

If that's the case, can you let me know how you deployed the website content? Did you use the CLI or CloudFormation instructions or did you upload the content some other way?

**Comment by rongqiibri** [comment] 2018-09-12 18:16
I used CLI
I see in ride.html this line <script src="js/vendor/aws-cognito-sdk.min.js"></script>, no .map suffix.
Below is the real link and maybe you can try to register and signin:
https://s3.us-east-2.amazonaws.com/wilddrydes-rong-qi/register.html

I will clean up everything and repeat the process tomorrow.  It did work for me yesterday. Thanks very much!

**Comment by mikedeck** [comment] 2018-09-12 19:06
I just realized, the .map extension is there because your browser is requesting source maps. That's why the page loaded successfully. I think you can ignore those errors for the .map resources.

That said, you are not using the website hosting endpoint for S3 which is causing other problems. Please make sure you follow the instructions for enabling website hosting and then use the URL provided in the console for the website endpoint.

I'm going to close this for now, but please reopen if you still have issues.

**Closed by mikedeck** 2018-09-12 19:06 UTC

**Comment by rongqiibri** [comment] 2018-09-12 20:27
You are right. Problem solved.

If I open my S3 bucket and there is a link for each html file and that is the one I used:
https://s3.us-east-2.amazonaws.com/wilddrydes-rrgg-rg/ride.html

The right link should be:
http://wilddrydes-rrgg-rg.s3-website.us-east-2.amazonaws.com/ride.html

Thanks very much!
