### ISSUE TITLE
Needed to execute template.yml file twice to get changes into API Gateway

### ISSUE THREAD

**Issue by devinbostIL** [aws-samples/aws-serverless-workshops#80] opened 2017-12-02 07:00 UTC
@samdengler , thanks for the help you provided me today during the workshop at the AWS conference. I was going through the DevOps workshop, and I noticed something unexpected that suggested the possibility of a bug. While working through the "API Enhancement" section of:
[DevOps/2_ContinuousDeliveryPipeline](https://github.com/awslabs/aws-serverless-workshops/tree/master/DevOps/2_ContinuousDeliveryPipeline)
after I pushed my changes via git into the remote origin and confirmed that the source, build, and deploy steps ran and completed successfully in CodeStar and confirmed in the pipeline history that the changes to the template.yml file were indeed included in the deployment, when I checked API Gateway and refreshed the page, the PUT action was still missing from /unicorns/{name}. (The GET action for that path was created, however.)
I wasn't sure how to get the deployment to re-run the template file, so I changed the template.yml file by removing a newline character from the very end of the file. I then pushed this change into origin, and after the CodeStar pipeline completed the deployment task, to my great surprise, in API Gateway, the PUT action had miraculously been created as expected.

Is there a reason I needed to execute the task twice to get the changes to propagate? I'm wondering if I experienced another known issue. Any ideas?

**Comment by mikedeck** [comment] 2018-04-05 23:57
I can't reproduce this.

CloudFormation should ensure that the state of your resources accurately reflects the deployed template. If you run into this again, I would take a look at the "Template" tab in the CloudFormation console when you have your stack selected to ensure that the template you deployed is in fact the one you intended. I have made mistakes in the past where I forgot to save my template in my editor before deploying which can result in this kind of issue.

I'm going to close this for now, but if you have a case in the future where the template from the CloudFormation console does not match the state of your deployed resource, please keep the stack around and open a support case through the AWS console.

**Closed by mikedeck** 2018-04-05 23:57 UTC
